server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka: # 配置Eureka客户端，将其连接到运行在http://127.0.0.1:10086/eureka的Eureka服务端
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka